# Generated by Django 5.1.7 on 2025-03-18 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_name', models.CharField(max_length=100)),
                ('common_name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('age_estimate', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('rescue_date', models.DateField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('In Treatment', 'In Treatment'), ('Recovering', 'Recovering')], default='Available', max_length=20)),
                ('additional_info', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='animals.animalcategory')),
            ],
        ),
    ]
